### ISSUE TITLE
Error loading custom_components.lightpack.light. Make sure all dependencies are installed

### ISSUE THREAD

**Issue by master-kenobi** [mihalski/homeassistant#2]
Hi,

I just installed the latest version on HA 0.88.2 but it gives out this error...

```
ERROR (MainThread) [homeassistant.loader] Error loading custom_components.lightpack.light. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/lightpack/light.py", line 121, in <module>
    class Lightpack(Light):
  File "/config/custom_components/lightpack/light.py", line 123, in Lightpack
    import lightpack
  File "/config/deps/lib/python3.7/site-packages/lightpack.py", line 6, in <module>
    from boltons import socketutils
ModuleNotFoundError: No module named 'boltons'
```

Please help.

**Comment by dobrynski** [comment]
Please see https://community.home-assistant.io/t/lightpack-assistance/102790/5
I have not yet uncovered the cause for this issue.

**Comment by tooljose88** [comment]
I have fixed it with the Portainer shell (installed from hassio) in the HomeAssistant container, and with the command:
```pip3.7 install --target=/config/deps/lib/python3.7/site-packages/ boltons```

Alternatively, if you are using a non Dockered HA, like hassbian, with a simple 
```pip3.7 install boltons```
it should work. This is just a bypass of the issue
